[project]
name = 'school-lunch-funding'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donation-pool]
path = 'contracts/donation-pool.clar'
clarity_version = 3
epoch = 3.1

[contracts.meal-distribution]
path = 'contracts/meal-distribution.clar'
clarity_version = 3
epoch = 3.1

[contracts.student-verification]
path = 'contracts/student-verification.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
